version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysqlDB
    restart: always
    env_file:
      - .envMysql
    ports:
      - "3306:3306"
    volumes:
      - ./scriptSql/migration.sql:/docker-entrypoint-initdb.d/migration.sql
